Repository googleinterns/zoomtube, pull requests merged in 2020-08, with the labels that each got.

#88 Update web.xml to require login for viewing lectures
  src/main/java/com/googleinterns/zoomtube/servlets/AuthenticationServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/index.html
  src/main/webapp/lecture-list.html
  src/main/webapp/list.html
  src/main/webapp/view.html
Labels: P0, improvements

#90 Adds LectureUtil class
  src/main/java/com/googleinterns/zoomtube/data/Lecture.java
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/java/com/googleinterns/zoomtube/utils/LectureUtil.java
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
  src/test/java/com/googleinterns/zoomtube/utils/LectureUtilTest.java
Labels: P0, internal-cleanup, lecture

#54 Adds Lecture Servlet that adds and displays Lectures
  pom.xml
  src/main/java/com/googleinterns/zoomtube/data/Lecture.java
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/java/com/googleinterns/zoomtube/utils/LectureUtil.java
  src/main/webapp/lectures.js
  src/main/webapp/list.html
  src/main/webapp/view.js
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
  src/test/java/com/googleinterns/zoomtube/utils/LectureUtilTest.java
Labels: lecture

#55 Adds video iFrame to lecture-view.html
  CODEOWNERS
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/webapp/lectures.js
  src/main/webapp/video.js
  src/main/webapp/view.html
  src/main/webapp/view.js
Labels: video

#97 Add CommentUtil class for converting between Entity and Comment
  src/main/java/com/googleinterns/zoomtube/data/Comment.java
  src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
  src/main/java/com/googleinterns/zoomtube/utils/CommentUtil.java
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
  src/test/java/com/googleinterns/zoomtube/utils/CommentUtilTest.java
Labels: P1, internal-cleanup

#100 Adds Styling to Lecture List
  src/main/webapp/fonts/product-sans/ProductSansBold.ttf
  src/main/webapp/fonts/product-sans/ProductSansBoldItalic.ttf
  src/main/webapp/fonts/product-sans/ProductSansItalic.ttf
  src/main/webapp/fonts/product-sans/ProductSansRegular.ttf
  src/main/webapp/lectures.js
  src/main/webapp/list.html
  src/main/webapp/style.css
Labels: design, internal-cleanup, lecture

#102 Fix comment field names in javascript
  src/main/webapp/discussion.js
Labels: P0, bug, discussions

#101 Fix redirect error in master
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
Labels: bug

#110 Move authentication code to auth.js
  src/main/webapp/auth.js
  src/main/webapp/discussion.js
  src/main/webapp/view.html
Labels: P0, internal-cleanup

#36 Store the Transcript Lines in Datastore and as JSON using hardcoded lecture and video ids.
  .gitignore
  WEB-INF/appengine-generated/local_db.bin
  index.yaml
  pom.xml
  src/main/java/com/googleinterns/zoomtube/data/Lecture.java
  src/main/java/com/googleinterns/zoomtube/data/TranscriptLine.java
  src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
  src/main/webapp/transcript.js
  src/main/webapp/view.html
  src/main/webapp/view.js
  src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
Labels: transcript

#46 Append the transcript lines to the DOM.
  src/main/java/com/googleinterns/zoomtube/data/TranscriptLine.java
  src/main/webapp/transcript.js
Labels: transcript

#52 Update Layout of Transcript on the DOM.
  src/main/java/com/googleinterns/zoomtube/data/TranscriptLine.java
  src/main/java/com/googleinterns/zoomtube/servlets/DeleteTranscriptServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
  src/main/webapp/transcript.js
  src/main/webapp/view.html
  src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
Labels: transcript

#111 Arrange the layout of view.html using bootstrap
  src/main/webapp/discussion.js
  src/main/webapp/style.css
  src/main/webapp/view.html
Labels: P0, design

#117 Add timestamps.js for timestamp-related functions used in multiple other javascript files
  src/main/java/com/googleinterns/zoomtube/servlets/DeleteTranscriptServlet.java
  src/main/webapp/timestamps.js
  src/main/webapp/transcript.js
  src/main/webapp/view.html
Labels: P1, internal-cleanup

#112 Add seeking functions for syncing
  src/main/webapp/discussion.js
  src/main/webapp/syncronizer.js
  src/main/webapp/transcript.js
  src/main/webapp/video.js
  src/main/webapp/view.html
  src/main/webapp/view.js
Labels: discussions, transcript, video

#132 Restructure webapp directory
  .github/workflows/lint.yml
  makefile
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/global.css
  src/main/webapp/index.html
  src/main/webapp/lectures/index.html
  src/main/webapp/lectures/lectures.js
  src/main/webapp/synchronizer.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/index.html
  src/main/webapp/view/transcript/transcript.js
  src/main/webapp/view/video/video.js
  src/main/webapp/view/view.js
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
Labels: P0, internal-cleanup

#133 Split CSS into multiple page-specific files
  .github/workflows/lint.yml
  makefile
  src/main/webapp/lectures/index.html
  src/main/webapp/lectures/lecture-list.css
  src/main/webapp/lectures/lectures.js
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
Labels: P0, internal-cleanup

#114 Use Bootstrap to make discussion section match design mock
  .eslintrc.json
  src/main/webapp/global.css
  src/main/webapp/lectures/index.html
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
Labels: P0, design, discussions

#128 Use unescapeXml when parsing XML for transcript
  pom.xml
  src/main/java/com/googleinterns/zoomtube/servlets/AuthenticationServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
  src/test/java/com/googleinterns/zoomtube/servlets/AuthenticationServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
Labels: P1, improvements, transcript

#135 Add a pre-commit hook to test and lint code locally
  .githooks/pre-commit
  README.md
  makefile
Labels: P1, internal-cleanup

#96 Move static Transcript methods and attributes into a Util class.
  pom.xml
  src/main/java/com/googleinterns/zoomtube/data/TranscriptLine.java
  src/main/java/com/googleinterns/zoomtube/servlets/DeleteTranscriptServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
  src/main/java/com/googleinterns/zoomtube/utils/TranscriptLineUtil.java
  src/main/webapp/index.html
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
  src/test/java/com/googleinterns/zoomtube/utils/TranscriptLineUtilTest.java
Labels: P0, internal-cleanup, transcript

#130 Refactor loadTranscript to only fetch from datastore.
  src/main/webapp/view/transcript/transcript.js
Labels: P0, transcript

#119 Adds landing page with project description
  src/main/webapp/index.html
  src/main/webapp/landing-page.css
  src/main/webapp/lectures/lecture-list.css
Labels: P1, design

#137 Removes dual inits in TranscriptServlet
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
  src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
Labels: P1, internal-cleanup

#142 Remove local_db.bin
  WEB-INF/appengine-generated/local_db.bin
Labels: P1, internal-cleanup

#151 Update LectureServletTest test video link to use a captioned video.
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
Labels: P0, bug, transcript

#153 Update transcript methods to use the Lecture Key rather than the Lecture Id.
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
  src/main/java/com/googleinterns/zoomtube/utils/TranscriptLineUtil.java
  src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
  src/test/java/com/googleinterns/zoomtube/utils/TranscriptLineUtilTest.java
Labels: P0, internal-cleanup, transcript

#150 Modifies LectureServlet to respond with one lecture
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/webapp/view/view.js
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
Labels: P0, internal-cleanup, lecture

#155 Automatically Scroll the Transcript as a Video Plays Forward Without Seeking Backwards
  src/main/webapp/timestamps.js
  src/main/webapp/view/transcript/transcript.js
Labels: P0, Synchronization, transcript

#162 Add and Remove Bold for the Current Transcript Line.
  src/main/webapp/view/transcript/transcript.js
Labels: P1, Synchronization, design, transcript

#152 Use long milliseconds for video timestamps instead of Date
  .githooks/pre-push
  src/main/java/com/googleinterns/zoomtube/data/Comment.java
  src/main/java/com/googleinterns/zoomtube/data/TranscriptLine.java
  src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
  src/main/java/com/googleinterns/zoomtube/transcriptParser/TranscriptParser.java
  src/main/java/com/googleinterns/zoomtube/utils/CommentUtil.java
  src/main/java/com/googleinterns/zoomtube/utils/TranscriptLineUtil.java
  src/main/webapp/timestamps.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/transcript/transcript.js
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
  src/test/java/com/googleinterns/zoomtube/utils/CommentUtilTest.java
  src/test/java/com/googleinterns/zoomtube/utils/TranscriptLineUtilTest.java
Labels: P0, Synchronization, internal-cleanup

#167 Fix height of transcript container.
  src/main/webapp/view/lecture-view.css
Labels: P0, bug, synchronization, transcript

#160 Removes extra slash in URL
  src/main/webapp/lectures/lectures.js
Labels: P2, internal-cleanup, lecture

#156 Removes videoId from URL
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/webapp/lectures/lectures.js
  src/main/webapp/view/transcript/transcript.js
  src/main/webapp/view/video/video.js
  src/main/webapp/view/view.js
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
Labels: P0, internal-cleanup, lecture, video

#174 Update seekTranscript to use long instead of Date for time.
  src/main/webapp/timestamps.js
  src/main/webapp/view/transcript/transcript.js
Labels: P0, bug, synchronization, transcript

#177 Remove unused imports and sendPostToTranscript method.
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
  src/main/webapp/view/transcript/transcript.js
  src/test/java/com/googleinterns/zoomtube/servlets/AuthenticationServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/LectureListServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
  src/test/java/com/googleinterns/zoomtube/transcriptParser/TranscriptParserTest.java
  src/test/java/com/googleinterns/zoomtube/utils/LectureUtilTest.java
  src/test/java/com/googleinterns/zoomtube/utils/TranscriptLineUtilTest.java
Labels: P2, internal-cleanup

#154 Display current time in new comment area, and submit to servlet
  src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
  src/main/webapp/timestamps.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/index.html
Labels: P0, discussions, synchronization

#170 Automatically scroll discussion to relevant comments
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/lecture-view.css
Labels: P1, discussions, synchronization

#181 Bold the transcript line as the video seeks.
  src/main/webapp/view/transcript/transcript.js
Labels: P0, synchronization, transcript

#200 Re-add URL slashes
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/webapp/index.html
  src/main/webapp/lectures/lectures.js
  src/main/webapp/view/index.html
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
Labels: P0, bug, internal-cleanup

#202 Update index.yaml to new Lecture and Comment field names
  index.yaml
Labels: P0

#198 Fix bug in which the first transcript line is not highlighted.
  src/main/webapp/view/transcript/transcript.js
Labels: P0, bug, synchronization, transcript

#205 Update height of the transcript container.
  src/main/webapp/view/lecture-view.css
  src/main/webapp/view/transcript/transcript.js
Labels: P0, bug, transcript

#206 Fixed header margin and font weight
  src/main/webapp/global.css
  src/main/webapp/landing-page.css
Labels: P2, bug

#193 Add template for transcript line.
  src/main/webapp/view/index.html
Labels: P1, internal-cleanup, transcript

#217 Make ZoomTube link to About page
  src/main/webapp/global.css
  src/main/webapp/index.html
  src/main/webapp/lectures/index.html
Labels: bug, design

#213 Added lecture name to the header of view page
  src/main/webapp/global.css
  src/main/webapp/index.html
  src/main/webapp/lectures/index.html
  src/main/webapp/view/view.js
Labels: P2, design, lecture

#187 Require parameters in TranscriptServlet
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
  src/main/webapp/view/transcript/transcript.js
  src/main/webapp/view/view.js
  src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
Labels: P1, internal-cleanup, transcript

#186 Require parameters in LectureServlet
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/java/com/googleinterns/zoomtube/utils/LectureUtil.java
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
Labels: P1, internal-cleanup, lecture

#222 Replace javascript @code with backticks
  src/main/webapp/lectures/lectures.js
  src/main/webapp/synchronizer.js
  src/main/webapp/timestamps.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/transcript/transcript.js
  src/main/webapp/view/video/video.js
  src/main/webapp/view/view.js
Labels: P2, internal-cleanup

#207 Remove logout/login button
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
Labels: P2, design

#175 Add comment types
  src/main/java/com/googleinterns/zoomtube/data/Comment.java
  src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
  src/main/java/com/googleinterns/zoomtube/utils/CommentUtil.java
  src/main/webapp/view/discussion/discussion.js
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
  src/test/java/com/googleinterns/zoomtube/utils/CommentUtilTest.java
Labels: P0, discussions

#184 Require parameters in DiscussionServlet
  src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
Labels: P1, discussions

#218 Improve responsiveness of synchronization
  src/main/webapp/synchronizer.js
  src/main/webapp/view/video/video.js
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
Labels: P0, synchronization

#234 Makes .js files modules
  .eslintrc.json
  src/main/webapp/auth.js
  src/main/webapp/lectures/lectures.js
  src/main/webapp/synchronizer.js
  src/main/webapp/timestamps.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/index.html
  src/main/webapp/view/transcript/transcript.js
  src/main/webapp/view/video/video.js
  src/main/webapp/view/view.js
Labels: P0, internal-cleanup

#239 Fixes JavaScript unused vars validation errors in master
  src/main/webapp/synchronizer.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/video/video.js
Labels: P0, bug, internal-cleanup

#237 Add babel-eslint as parser
  .eslintrc.json
  makefile
  src/main/webapp/view/discussion/discussion.js
Labels: P0, dependencies, internal-cleanup

#223 Add a favicon for zoomtube.
  src/main/webapp/favicon.png
  src/main/webapp/index.html
  src/main/webapp/lectures/index.html
  src/main/webapp/view/index.html
Labels: P2, design

#228 Add function to create a time range string given the start and end time.
  src/main/webapp/timestamps.js
Labels: P2, internal-cleanup

#192 Convert the Transcript Line on the DOM to be a Custom Element.
  src/main/webapp/favicon.ico
  src/main/webapp/view/index.html
  src/main/webapp/view/transcript/transcript.js
Labels: P1, internal-cleanup, transcript

#221 Synchronize components with time in milliseconds
  src/main/webapp/synchronizer.js
  src/main/webapp/timestamps.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/transcript/transcript.js
  src/main/webapp/view/video/video.js
Labels: P1, internal-cleanup, synchronization

#255 Refactor loading of the Transcript Area into a class.
  src/main/webapp/view/transcript/transcript-area.js
  src/main/webapp/view/transcript/transcript.js
  src/main/webapp/view/view.js
Labels: P0, internal-cleanup, transcript

#252 Refactors synchronizer.js file to include a class
  src/main/webapp/synchronizer.js
  src/main/webapp/view/video/video.js
  src/main/webapp/view/view.js
Labels: P0, internal-cleanup, synchronization

#260 Refactors Video.js adding a Video class
  src/main/webapp/synchronizer.js
  src/main/webapp/view/video/video.js
  src/main/webapp/view/view.js
Labels: P0, video

#263 Adds ability to get current video time
  src/main/webapp/synchronizer.js
  src/main/webapp/view/video/video.js
  src/main/webapp/view/view.js
Labels: P0, video

#281 Use getClass when converting JSON into list of comments
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
Labels: P2, bug

#279 Adds IconFeedback class and IconFeedbackUtil class
  src/main/java/com/googleinterns/zoomtube/data/IconFeedback.java
  src/main/java/com/googleinterns/zoomtube/utils/IconFeedbackUtil.java
  src/test/java/com/googleinterns/zoomtube/utils/IconFeedbackUtilTest.java
Labels: P1, feedback

#292 Removes left over tests in event controller
  src/main/webapp/event-controller.js
Labels: P0, bug, internal-cleanup

#297 Reformat HTML to satisfy updated linter
  src/main/webapp/view/index.html
Labels: P0

#277 Add buttons for icon feedback
  src/main/webapp/feedback/icon-feedback.js
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
Labels: P1, feedback

#275 Refactor loadTranscript to use async.
  src/main/webapp/view/transcript/transcript-area.js
Labels: P0, transcript

#274 Add type tag to DiscussionComment
  src/main/webapp/view/discussion/discussion-comment.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/index.html
Labels: P0, design, discussions

#282 Fix minor layout and formatting inconsistencies
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
  src/main/webapp/view/transcript/transcript.js
Labels: P1, design

#273 Add transcript lines using a datastore Transaction
  src/main/java/com/googleinterns/zoomtube/transcriptParser/TranscriptParser.java
  src/main/java/com/googleinterns/zoomtube/utils/TranscriptLineUtil.java
Labels: P1, bug, transcript

#295 Insert new comments instead of reloading them all
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/discussion/discussion-comment.js
  src/main/webapp/view/discussion/discussion-manager.js
Labels: P0, discussions

#309 Remove global button style overrides, and restyle discussion buttons
  src/main/webapp/global.css
  src/main/webapp/index.html
  src/main/webapp/landing-page.css
  src/main/webapp/lectures/index.html
  src/main/webapp/lectures/lecture-list.css
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
Labels: P1, design

#310 Add type buttons for posting a new comment
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
Labels: P0, discussions

#286 Create a custom element to implement auto-scrolling for the transcript.
  src/main/webapp/scroll-container.js
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
  src/main/webapp/view/transcript/transcript-area.js
  src/main/webapp/view/transcript/transcript-seeker.js
Labels: P0, transcript

#294 Links Synchronizer to Video eliminating global scope
  src/main/webapp/synchronizer.js
  src/main/webapp/view/video/video.js
  src/main/webapp/view/view.js
Labels: P0, internal-cleanup, synchronization, video

#298 Refactors lecture-view.js to include classes
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.js
  src/main/webapp/view/transcript/transcript-area.js
  src/main/webapp/view/video/video.js
Labels: P0, internal-cleanup

#303 Adds event listeners for seeking
  src/main/webapp/synchronizer.js
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/lecture-view.js
  src/main/webapp/view/transcript/transcript-area.js
  src/main/webapp/view/transcript/transcript-seeker.js
  src/main/webapp/view/video/video.js
Labels: P0, internal-cleanup

#308 Stores feedback icon click in database
  src/main/java/com/googleinterns/zoomtube/servlets/IconFeedbackServlet.java
  src/main/java/com/googleinterns/zoomtube/utils/IconFeedbackUtil.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/feedback/icon-feedback.js
  src/test/java/com/googleinterns/zoomtube/servlets/IconFeedbackServletTest.java
Labels: P1, feedback

#327 Move comment reply form to end of replies
  src/main/webapp/view/discussion/discussion-comment.js
  src/main/webapp/view/index.html
Labels: P2, bug, discussions

#337 Clear the new comment textarea on post
  src/main/webapp/view/discussion/discussion-area.js
Labels: P2, bug, discussions

#314 Use scroll container in discussion area
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/discussion/discussion-comment.js
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
Labels: P0, design, discussions, synchronization

#326 Use Filter on videoId to detect duplicate lectures
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
Labels: P2, internal-cleanup, lecture

#302 Display an error message if there is no transcript available for the lecture.
  src/main/webapp/view/transcript/transcript-area.js
  src/main/webapp/view/transcript/transcript-seeker.js
Labels: P1, design, transcript

#315 Send redirect even on transcript error
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
Labels: P2, internal-cleanup, lecture

#306 Add comment indicator to trancriptLineElement.
  src/main/webapp/view/lecture-view.css
  src/main/webapp/view/transcript/transcript.js
Labels: P0, comment-indicator, design

#332 Allow users to hover over the comment indicators to reveal a popup.
  src/main/webapp/view/lecture-view.css
  src/main/webapp/view/transcript/transcript-area.js
  src/main/webapp/view/transcript/transcript.js
Labels: P2, comment-indicator, transcript

#317 Remove newlines from transcript line content
  src/main/java/com/googleinterns/zoomtube/transcriptParser/TranscriptParser.java
  src/test/java/com/googleinterns/zoomtube/transcriptParser/TranscriptParserTest.java
Labels: P2, transcript

#344 Add smooth scrolling to scroll containers
  src/main/webapp/global.css
  src/main/webapp/scroll-container.js
Labels: P2, synchronization

#323 Add TranscriptLine field to Comment
  src/main/java/com/googleinterns/zoomtube/data/Comment.java
  src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
  src/main/java/com/googleinterns/zoomtube/utils/CommentUtil.java
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/discussion/discussion-comment.js
  src/main/webapp/view/discussion/discussion-manager.js
  src/main/webapp/view/lecture-view.js
  src/main/webapp/view/view.js
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
  src/test/java/com/googleinterns/zoomtube/utils/CommentUtilTest.java
Labels: P0, comment-indicator, discussions, transcript

#357 Refactors timestamp.js to a class
  src/main/webapp/timestamp-util.js
  src/main/webapp/timestamps.js
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/discussion/discussion-comment.js
  src/main/webapp/view/transcript/transcript.js
  src/main/webapp/view/video/video.js
Labels: P1, internal-cleanup

#349 Removes view.js
  src/main/webapp/view/view.js
Labels: P0, internal-cleanup

#352 Adds seeking video function, makes video player private
  src/main/webapp/timestamp-util.js
  src/main/webapp/view/video/video.js
Labels: P1, internal-cleanup, synchronization, video

#347 Adds event listener for seeking video
  src/main/webapp/timestamp-util.js
  src/main/webapp/view/index.html
  src/main/webapp/view/video/video.js
Labels: P1, synchronization, video

#338 Allow users to seek by clicking on the transcript.
  src/main/webapp/view/lecture-view.css
  src/main/webapp/view/transcript/transcript-area.js
  src/main/webapp/view/transcript/transcript-seeker.js
  src/main/webapp/view/transcript/transcript.js
Labels: P0, synchronization, transcript
