Repository googleinterns/zoomtube, pull requests merged in 2020-09, with the labels that each got.

#321 Add function for incrementing the comment indicator.
  src/main/webapp/view/transcript/transcript-area.js
Labels: P0, comment-indicator

#362 Create a builder class to store the properties of a transcript language.
  src/main/java/com/googleinterns/zoomtube/data/TranscriptLanguage.java
Labels: P2, transcript

#358 Add load spinner to the transcript, lecture list, and comments.
  src/main/webapp/lectures/index.html
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
  src/main/webapp/view/transcript/transcript-area.js
Labels: P2, design, discussions, transcript, video

#339 Seek when a root comment's header is clicked
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/discussion/discussion-comment.js
  src/main/webapp/view/lecture-view.css
Labels: P0, discussions

#345 Add MarkAnsweredServlet and tests
  src/main/java/com/googleinterns/zoomtube/data/Comment.java
  src/main/java/com/googleinterns/zoomtube/servlets/MarkAnsweredServlet.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/index.html
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/MarkAnsweredServletTest.java
  src/test/java/com/googleinterns/zoomtube/utils/CommentUtilTest.java
Labels: P2, discussions

#368 Display comment creation time in the user's timezone
  src/main/webapp/view/discussion/discussion-comment.js
  src/main/webapp/view/discussion/discussion-manager.js
Labels: P0, bug, discussions

#311 Adds ability to get all icon feedback for a specific lecture
  src/main/java/com/googleinterns/zoomtube/data/IconFeedback.java
  src/main/java/com/googleinterns/zoomtube/servlets/IconFeedbackServlet.java
  src/main/webapp/feedback/icon-feedback.js
  src/test/java/com/googleinterns/zoomtube/servlets/IconFeedbackServletTest.java
Labels: P1, feedback

#360 Modifies icon feedback class to eliminate the need for window
  src/main/webapp/feedback/icon-feedback.js
  src/main/webapp/feedback/post-icon-feedback.js
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.js
Labels: P1, feedback

#370 Fix adding transcript line to comment post request
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/discussion/discussion-comment.js
Labels: P0, comment-indicator

#373 Make footer stick to bottom of window if possible
  src/main/webapp/global.css
  src/main/webapp/landing-page.css
  src/main/webapp/lectures/lecture-list.css
Labels: P1, bug, design

#375 Remove unused dependencies from pom.xml
  pom.xml
Labels: P2, internal-cleanup

#377 Update Discussion Comments in background
  src/main/webapp/view/discussion/discussion-area.js
Labels: P0, bug, discussions

#374 Throw Exception in tests, and cleanup imports
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/IconFeedbackServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/LectureListServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
  src/test/java/com/googleinterns/zoomtube/transcriptParser/TranscriptParserTest.java
  src/test/java/com/googleinterns/zoomtube/utils/CommentUtilTest.java
  src/test/java/com/googleinterns/zoomtube/utils/IconFeedbackUtilTest.java
  src/test/java/com/googleinterns/zoomtube/utils/LectureUtilTest.java
  src/test/java/com/googleinterns/zoomtube/utils/TranscriptLineUtilTest.java
Labels: P2, internal-cleanup

#381 Made video player dynamically adjust size
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
  src/main/webapp/view/video/video.js
Labels: P0, feedback, internal-cleanup

#389 Fix issue where the currentElement is not defined in scrollContainer
  src/main/webapp/scroll-container.js
Labels: P0, bug, synchronization

#391 Update storage setting for the local datastore test configuration.
  src/test/java/com/googleinterns/zoomtube/servlets/DiscussionServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/IconFeedbackServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/LectureListServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
  src/test/java/com/googleinterns/zoomtube/servlets/MarkAnsweredServletTest.java
Labels: P0, bug, feedback

#380 Call incrementCommentIndicatorAt() in DiscussionArea.
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/lecture-view.js
Labels: P1, comment-indicator, discussions, transcript

#390 Fix issue where comments can not be posted if there is no transcript.
  src/main/webapp/view/discussion/discussion-area.js
  src/main/webapp/view/discussion/discussion-manager.js
Labels: P0, bug, discussions, transcript

#396 Adds wrapper class for icon feedback
  src/main/webapp/feedback/icon-feedback-util.js
  src/main/webapp/feedback/interval-icon-feedback-count.js
Labels: P0, internal-cleanup

#369 Parses icon feedback
  src/main/webapp/feedback/interval-icon-feedback-count.js
  src/main/webapp/feedback/load-icon-feedback.js
  src/main/webapp/feedback/parsed-icon-feedback.js
Labels: P1, feedback

#364 Add button for changing question status
  src/main/webapp/view/discussion/discussion-comment.js
  src/main/webapp/view/discussion/discussion.js
  src/main/webapp/view/discussion/mark-answered-util.js
  src/main/webapp/view/index.html
Labels: P2, discussions

#363 Create a servlet for fetching the transcript language options.
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptLanguageServlet.java
  src/main/java/com/googleinterns/zoomtube/transcriptParser/TranscriptParser.java
  src/main/webapp/WEB-INF/web.xml
  src/test/java/com/googleinterns/zoomtube/servlets/TranscriptLanguageServletTest.java
Labels: P2, transcript, transcript-language

#371 Creates chart for icon feedback
  index.yaml
  src/main/java/com/googleinterns/zoomtube/servlets/TranscriptLanguageServlet.java
  src/main/webapp/feedback/icon-feedback-util.js
  src/main/webapp/feedback/icon-feedback.css
  src/main/webapp/feedback/index.html
  src/main/webapp/feedback/load-icon-feedback.js
  src/main/webapp/feedback/parsed-icon-feedback.js
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.js
Labels: P1, feedback

#392 Add svg feedback icons
  src/main/webapp/view/index.html
  src/main/webapp/view/lecture-view.css
Labels: P2, feedback

#372 Fetch the languages from the servlet and display them on the DOM.
  src/main/webapp/lectures/index.html
  src/main/webapp/lectures/lectures.js
Labels: P2, transcript, transcript-language

#378 Parse the transcript with the selected language.
  src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
  src/main/java/com/googleinterns/zoomtube/transcriptParser/TranscriptParser.java
  src/main/webapp/lectures/lectures.js
  src/main/webapp/view/discussion/discussion-area.js
  src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
  src/test/java/com/googleinterns/zoomtube/transcriptParser/TranscriptParserTest.java
Labels: P2, transcript, transcript-language

#367 Check and update displayed comment type when updating discussion
  src/main/webapp/view/discussion/discussion-comment.js
  src/main/webapp/view/discussion/discussion-manager.js
  src/main/webapp/view/discussion/mark-answered-endpoint.js
Labels: P2, discussions
